# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/project-portal/project-portal-backend"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "cargo"
    directory: "/stellar-core/carbon-asset-factory"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "cargo"
    directory: "/stellar-core/compliance-engine"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "cargo"
    directory: "/stellar-core/verifiable-registry"
    schedule:
      interval: "weekly"